### ISSUE TITLE
Make Windows build work

### ISSUE THREAD

**Issue by askonomm** [askonomm/tobey#6]
Since I use Linux, I lack a easy way to debug why the Windows build fails, so it would be great if someone with a Windows machine could check it out.

**Comment by AbdullahElsheshtawy** [comment]
I happen to be using windows as of right now and it's building just fine on visual studio 2022 community edition.
![image](https://github.com/user-attachments/assets/16b1e24e-b0f5-4e04-aa04-5b74d3e9df0b)

**Comment by AbdullahElsheshtawy** [comment]
would love to help if u encounter any problems before I switch back to linux.

**Comment by askonomm** [comment]
@AbdullahElsheshtawy I can't quite figure out why the build fails in Github Actions: https://github.com/askonomm/tobey/actions/runs/10548026577/job/29221427374

**Comment by AbdullahElsheshtawy** [comment]
![image](https://github.com/user-attachments/assets/5ca711d1-e5e0-4205-875f-2cdcd0399a76)
so, this is the issue. you do not have any operator overloading in tobey.cpp. I bet its mingw problem since its compiling just fine on MSVC.

**Comment by AbdullahElsheshtawy** [comment]
Iam installing mingw right now and will look into it further

**Comment by AbdullahElsheshtawy** [comment]
From my investigations i found that filesystem is not supported by the latest mingw g++ release 
![image](https://github.com/user-attachments/assets/07f4e0d2-5a70-4291-b6cc-bd5f87192937)
i even tried to invoke the compiler myself and this is the output std=c++17 (which is the max it partially supports) 
![image](https://github.com/user-attachments/assets/7535fcb3-9064-467b-b4e4-e0a049a0a926)
i suggest building with msvc since it supports all the features and the build runs just fine .

**Comment by askonomm** [comment]
Thank you @AbdullahElsheshtawy for the help! As of v0.2.11 there are now x86 and x64 builds for Windows as well.

**Comment by AbdullahElsheshtawy** [comment]
No problem!
